### ISSUE TITLE
First release checklist

### ISSUE THREAD

**Issue by PabloCorcho** [paranoya/population-synthesis-toolkit#28]
Here's a (non-exhaustive) list of pending items to have ready before the first release version:

- [x] Add documentation to all relevant classes/methods (PR #24).
- [x] Design the contents to be included on the online documentation (#29).
- [x] Include a default SSP model for tutorials/demos (WI, #22).
- [x] Refactor the directory tests (by `tutorials`) and test all methods.
- [x] Create a release branch that does not include `fitting_module`.
- [x] Release on pypi

**Comment by PabloCorcho** [comment]
@paranoya check tutorials

**Comment by PabloCorcho** [comment]
@Danieljl96 let us know if fitting module is ready for release

**Comment by paranoya** [comment]
Shall we mark "Refactor the directory tests (by tutorials) and test all methods"?
I mean, "all"?
